= Marco D'Agostini
I'm a Venezuelan-Italian Software Developer with a degree in Mechanical Maintenance Engineer

.Summary
****
+5 years of experience in *Web Development*, using mostly React, NodeJs/Express, Mysql, Ruby/Sinatra, Python/Flask. +
+7 years using *Linux based systems*, 5 years managing home servers (Raspberry Pi), and 2 years managing production servers. +
+15 years doing *Electronic projects*, using Raspberry Pi, Arduino or PICs.
****

== Experience

- *Contatrib / Mi Factura Perú*  --  2019 - Current  --  _(Not yet published)_ +
I'm co-leading a team of 6 people in building a web-based ERP using *React*, *NodeJs/Express*, *Mysql* and *Docker*.

- http://www.bolivarparalelo.com/beta[Bolivar Paralelo (beta)]  --  2018 - Current  --  https://github.com/madacol/bolivarparalelo[source] +
A hobbie project that analyzes http://www.localbitcoins.com to get currency rates in bitcoins, calculate cross rates between currencies and render history graphs. Mostly oriented to Venezuelans, but currencies are customizable. +
Built with *Svelte*, *Ruby/Sinatra* and *PostgreSql* (with ORM)

- https://www.youtube.com/watch?v=MHU5xQRTyus[Arduino controlled conveyor oven]  --  2018 - Current  --  https://github.com/madacol/ArduinoOven[source] +
Designed, built and developed the electronic system using an *Arduino Mega* with a Touchscreen interface. +
I implemented software-based-PIDs to control temperatures and conveyor's speed. +
A *Raspberry Pi Zero* is connected to the Arduino, which logs data from Serial port, and allows me to connect remotely to flash the Arduino. +
https://github.com/madacol/webOven[Simple web interface] that runs in the RPi, to show history graphs from the logs. +
Built with *Python/Flask* and used *matplotlib* for graphing.

- http://www.mifacturaperu.com/[Mi Factura Perú]  --  2019 +
Built the website with *PHP/Laravel*. +
Mantained a desktop app that help businesses make electronic invoices, built with *VB.NET/WPF*, *PHP/Slim* and *Mysql*.

- https://www.youtube.com/watch?v=wu8dKf8xgoI[Helical Milling]  --  ~ 2013  --  https://github.com/madacol/helical-milling[source] +
Designed, built and developed the electronic system using a *PIC16F877*

- https://www.youtube.com/watch?v=joTXaflXwJw[CNC router]  --  ~ 2009 - 2012 +
Built and adapted the electronic system

== Contact

- *Email*: madacol10@gmail.com
- *GitHub*: https://github.com/madacol
- *Twitter*: https://twitter.com/madacol

<<<

== Other Profiles

- *StackOverflow*: https://stackoverflow.com/users/3163120/madacol
- *LinkedIn*: https://www.linkedin.com/in/marco-d-agostini-colaiuda-8ab0a254/
- *Youtube*: https://www.youtube.com/user/madacol/videos
- *Facebook*: https://www.facebook.com/madacol10